### PR TITLE
Add Horizontal Swing and Converti Support

### PR DESCRIPTION
**Pull request by deCodeIt**
Add support for horizontal swing as well as Converti.

Tested on [Panasonic 1.5 Ton 4 Star Wi-Fi Inverter Smart Split AC (Copper Condenser, 7 in 1 Convertible with AI, 4 Way Swing, PM Filter, CS/CU-NU18YKY4W,2023 Model, White)](https://www.panasonic.com/in/consumer/air-conditioners/split-ac/cs-cu-nu18yky4w.html)

### CODE REVIEW

**Comment by deCodeIt** [comment]
Tagging for review @rkzofficial

**Comment by rkzofficial** [comment]
@deCodeIt

First of all, thank you very much for raising the pull request.

This package is being used internally by ha-mirae-ac (Home assistant module).
I believe there is currently no way to implement this convertible mode in the home assistant UI. Please correct me if I am mistaken.

Do you have any idea if this is possible?

**Comment by deCodeIt** [comment]
> @deCodeIt
> 
> First of all, thank you very much for raising the pull request.
> 
> This package is being used internally by ha-mirae-ac (Home assistant module). I believe there is currently no way to implement this convertible mode in the home assistant UI. Please correct me if I am mistaken.
> 
> Do you have any idea if this is possible?

Yes, for the Converti mode, I was planning on using the `preset` to add converti options over there along with existing ones.
https://developers.home-assistant.io/docs/core/entity/climate/#presets

**Comment by deCodeIt** [comment]
@rkzofficial If this looks good to you, can you merge it so I can use it to enhance `ha-mirae-ac`. That's my ultimate goal to make this patch.

**Comment by rkzofficial** [comment]
> @rkzofficial If this looks good to you, can you merge it so I can use it to enhance `ha-mirae-ac`. That's my ultimate goal to make this patch.

Sure, once I am back home I will do that.

**Review by rkzofficial — APPROVED** [review]

**Comment by deCodeIt** [comment]
@rkzofficial Can you publish the main branch to npm so I can use it to enhance ha-miraie-ac repo

**Pull request merged**
