### PR TITLE
Add debug logs

### PR DESCRIPTION
**Pull request by deCodeIt**
These debug logs will help add new features and ease up library maintenance.

### CODE REVIEW

**Comment by deCodeIt** [comment]
Tagging @rkzofficial to take a look. Logs will help us in the long run. There is also a user requesting support for heat mode. It would make adding such features easier if we have the logs with us thereby avoiding access to credentials

**Comment by rkzofficial** [comment]
@deCodeIt Thanks for the pull request. 

Everything looks good, let's merge it.

**Comment by deCodeIt** [comment]
@rkzofficial You'll also need to release the latest package on PyPi

**Comment by rkzofficial** [comment]
> @rkzofficial You'll also need to release the latest package on PyPi

Yes I am doing that. I was little busy.

**Pull request merged**
